name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '22'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file api/pom.xml